### ISSUE TITLE
Not working with SublimeLinter v4

### ISSUE THREAD

**Issue by nhoffmann** [SublimeLinter/SublimeLinter-haml-lint#8]
Thanks for the great plugin. Unfortunately it is not playing nicely with SublimeLinter v4.

The linter just crashes when linting haml files:

```
SublimeLinter: #5 hamllint _user_menu.html.haml ERROR:

 Linter crashed.

Traceback (most recent call last):
  File "lint.backend in /Users/nho/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 97, in execute_lint_task
  File "lint.linter in /Users/nho/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 794, in lint
  File "lint.linter in /Users/nho/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 514, in get_cmd
  File "lint.linter in /Users/nho/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 554, in build_cmd
  File "lint.linter in /Users/nho/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter.sublime-package", line 594, in insert_args
  File "linter in /Users/nho/Library/Application Support/Sublime Text 3/Installed Packages/SublimeLinter-contrib-haml-lint.sublime-package", line 38, in build_args
AttributeError: 'module' object has no attribute 'find_file'
```

**Comment by kaste** [comment]
Maybe https://github.com/jeroenj/SublimeLinter-contrib-haml-lint/pull/9

**Comment by andrewkendall** [comment]
What is the current status with this patch? Currently installing via Package Control - Install Package looks like it's still installing the incompatible version 1.0.2. Is it just a case of waiting or is there an alternative install method that I'm missing?

**Comment by braver** [comment]
The status is that I forgot all about it, but we should be able to merge our fix and ship it soon.

**Comment by andrewkendall** [comment]
No problem at all. Thank you. Very much appreciate your work on this.

**Comment by braver** [comment]
@nhoffmann @andrewkendall we have a proposed fix at https://github.com/SublimeLinter/SublimeLinter-haml-lint/pull/9 that *probably* works. Can one of you verify, because sadly we don't know every language under the sun 😎

**Comment by andrewkendall** [comment]
I've just created a package from the patched code and can confirm the error is fixed and as far as I can see it's now working as expected. Let me know if you'd like any more details.

**Comment by braver** [comment]
Thanks!
